#!/bin/sh
docker run --rm --runtime=nvidia -d --name=blender \
  -v /tmp:/mnt \
  -e NVIDIA_VISIBLE_DEVICES=3,7,9 \
  -e BLEND_DIR=/mnt/postkino/shot/ \
  -e FRAME_FNAME=/mnt/postkino/shot/frame%04d.exr \
  -e OCIO="/mnt/OpenColorIO-Configs/aces_1.0.3/config.ocio" \
  emanaev/blender:0.5
docker logs -f blender
